#!/usr/bin/env python3
//task-0
import pymongo


client = pymongo.MongoClient("mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb")
database_list = client.list_database_names()
for i in database_list:
    print(i)
client.close()
